In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [3]:
train_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,low_risk,n,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,low_risk,n,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,low_risk,n,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,low_risk,n,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

In [4]:
test_df.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,67991,67991,40000.0,0.0819,814.70,MORTGAGE,140000.0,Not Verified,low_risk,n,...,97.7,0.0,0.0,0.0,527975.0,70914.0,74600.0,99475.0,N,N
1,25429,25429,6000.0,0.1524,208.70,RENT,55000.0,Not Verified,low_risk,n,...,66.7,0.0,0.0,0.0,34628.0,23460.0,5900.0,23628.0,N,N
2,38496,38496,3600.0,0.1695,128.27,RENT,42000.0,Not Verified,low_risk,n,...,100.0,0.0,0.0,0.0,23100.0,19183.0,7300.0,15000.0,N,N
3,19667,19667,20000.0,0.1524,478.33,RENT,100000.0,Not Verified,low_risk,n,...,100.0,50.0,0.0,0.0,56481.0,43817.0,13800.0,35981.0,N,N
4,37505,37505,3600.0,0.1240,120.27,RENT,50000.0,Not Verified,low_risk,n,...,100.0,25.0,0.0,0.0,45977.0,32448.0,21000.0,24977.0,N,N

# Convert categorical data to numeric and separate target feature for TRAINING data

In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [6]:
# Create the X feature vector (train data)
X_train = train_df.drop('loan_status', axis=1)
X_train.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,57107,57107,13375.0,0.1797,483.34,MORTGAGE,223000.0,Not Verified,n,29.99,...,100.0,50.0,0.0,0.0,577150.0,122018.0,32000.0,170200.0,N,N
1,141451,141451,21000.0,0.1308,478.68,MORTGAGE,123000.0,Source Verified,n,11.26,...,85.0,33.3,0.0,0.0,132750.0,27896.0,15900.0,35398.0,N,N
2,321143,321143,20000.0,0.1240,448.95,MORTGAGE,197000.0,Source Verified,n,11.28,...,85.7,33.3,0.0,0.0,628160.0,114043.0,22600.0,90340.0,N,N
3,11778,11778,3000.0,0.1240,100.22,RENT,45000.0,Not Verified,n,18.08,...,100.0,16.7,1.0,0.0,42006.0,20761.0,19900.0,15406.0,N,N
4,169382,169382,30000.0,0.1612,1056.49,MORTGAGE,133000.0,Source Verified,n,27.77,...,100.0,66.7,0.0,0.0,283248.0,109056.0,79500.0,58778.0,N,N

# Index and unnamed columns can be dropped or made into index

In [7]:
# Display the features with binary data for use with label encoder
X_train[["application_type", "debt_settlement_flag","hardship_flag","initial_list_status","pymnt_plan"]].head()

,application_type,debt_settlement_flag,hardship_flag,initial_list_status,pymnt_plan
0,Individual,N,N,w,n
1,Individual,N,N,w,n
2,Individual,N,N,w,n
3,Individual,N,N,w,n
4,Individual,N,N,w,n

In [8]:
# Use Label Encoder to preprocess binary text features
le = LabelEncoder()
X_train["application_type"] = le.fit_transform(X_train["application_type"])
print("Label encoder for application_type: ", le.classes_)
X_train["debt_settlement_flag"] = le.fit_transform(X_train["debt_settlement_flag"])
print("Label encoder for deb_settlement_flag: ", le.classes_)
X_train["hardship_flag"] = le.fit_transform(X_train["hardship_flag"])
print("Label encoder for hardship_flag: ", le.classes_)
X_train["initial_list_status"] = le.fit_transform(X_train["initial_list_status"])
print("Label encoder for initial_list_status: ", le.classes_)
X_train["pymnt_plan"] = le.fit_transform(X_train["pymnt_plan"])
print("Label encoder for pymnt_plan: ", le.classes_)

Label encoder for application_type:  ['Individual' 'Joint App']
Label encoder for deb_settlement_flag:  ['N' 'Y']
Label encoder for hardship_flag:  ['N' 'Y']
Label encoder for initial_list_status:  ['f' 'w']
Label encoder for pymnt_plan:  ['n']

In [9]:
# Display the features with binary data after label encoding
X_train[["application_type", "debt_settlement_flag","hardship_flag","initial_list_status","pymnt_plan"]].head()

,application_type,debt_settlement_flag,hardship_flag,initial_list_status,pymnt_plan
0,0,0,0,1,0
1,0,0,0,1,0
2,0,0,0,1,0
3,0,0,0,1,0
4,0,0,0,1,0

In [10]:
# Use pd.get_dummies for all other categorical features
X_train = pd.get_dummies(X_train, drop_first=True)
print(X_train.columns)
X_train.head()

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'pymnt_plan', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'initial_list_status',
       'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'debt_settlement_flag',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Source Verified', 'verification_status_Verified'],
      dtype='object')

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Source Verified,verification_status_Verified
0,57107,57107,13375.0,0.1797,483.34,223000.0,0,29.99,0.0,0.0,...,122018.0,32000.0,170200.0,0,0,1,0,0,0,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,0,11.26,2.0,0.0,...,27896.0,15900.0,35398.0,0,0,1,0,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,0,11.28,0.0,0.0,...,114043.0,22600.0,90340.0,0,0,1,0,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,0,18.08,0.0,0.0,...,20761.0,19900.0,15406.0,0,0,0,0,1,0,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,0,27.77,0.0,2.0,...,109056.0,79500.0,58778.0,0,0,1,0,0,1,0

In [12]:
# Create the y-label (train data)
# Convert output labels to 0 and 1 with label encoder
y_train = le.fit_transform(train_df['loan_status'])
print("Label Encoder classes (train): ", le.classes_)
print("y_train (train): ", y_train)

Label Encoder classes (train):  ['high_risk' 'low_risk']
y_train (train):  [1 1 1 ... 0 0 0]

# Convert categorical data to numeric and separate target feature for TESTING data

In [13]:
# Create the X feature vector (test data)
X_test = test_df.drop('loan_status', axis=1)

# Use Label Encoder to preprocess binary text features
le = LabelEncoder()
X_test["application_type"] = le.fit_transform(X_test["application_type"])
print("Label encoder for application_type: ", le.classes_)
X_test["debt_settlement_flag"] = le.fit_transform(X_test["debt_settlement_flag"])
print("Label encoder for deb_settlement_flag: ", le.classes_)
X_test["hardship_flag"] = le.fit_transform(X_test["hardship_flag"])
print("Label encoder for hardship_flag: ", le.classes_)
X_test["initial_list_status"] = le.fit_transform(X_test["initial_list_status"])
print("Label encoder for initial_list_status: ", le.classes_)
X_test["pymnt_plan"] = le.fit_transform(X_test["pymnt_plan"])
print("Label encoder for pymnt_plan: ", le.classes_)

# Use pd.dummies for all other categorical features
X_test = pd.get_dummies(X_test, drop_first=True)
print(X_test.columns)
X_test.head()

Label encoder for application_type:  ['Individual' 'Joint App']
Label encoder for deb_settlement_flag:  ['N']
Label encoder for hardship_flag:  ['N' 'Y']
Label encoder for initial_list_status:  ['f' 'w']
Label encoder for pymnt_plan:  ['n']
Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'pymnt_plan', 'dti', 'delinq_2yrs', 'inq_last_6mths',
       'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'initial_list_status',
       'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'policy_code', 'application_type',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'hardship_flag', 'debt_settlement_flag',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Source Verified', 'verification_status_Verified'],
      dtype='object')

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Source Verified,verification_status_Verified
0,67991,67991,40000.0,0.0819,814.70,140000.0,0,19.75,0.0,1.0,...,70914.0,74600.0,99475.0,0,0,1,0,0,0,0
1,25429,25429,6000.0,0.1524,208.70,55000.0,0,11.52,2.0,0.0,...,23460.0,5900.0,23628.0,0,0,0,0,1,0,0
2,38496,38496,3600.0,0.1695,128.27,42000.0,0,6.74,0.0,0.0,...,19183.0,7300.0,15000.0,0,0,0,0,1,0,0
3,19667,19667,20000.0,0.1524,478.33,100000.0,0,12.13,0.0,2.0,...,43817.0,13800.0,35981.0,0,0,0,0,1,0,0
4,37505,37505,3600.0,0.1240,120.27,50000.0,0,16.08,0.0,3.0,...,32448.0,21000.0,24977.0,0,0,0,0,1,0,0

In [14]:
# Create the y-label (test data)
# Convert output labels to 0 and 1
y_test = le.fit_transform(test_df['loan_status'])
print("Label Encoder classes (test): ", le.classes_)
print("y_test (test): ", y_test)

Label Encoder classes (test):  ['high_risk' 'low_risk']
y_test (test):  [1 1 1 ... 0 0 0]

In [15]:
# add missing dummy variables to testing set
## NOTE: Shapes for (X_train, y_train) are currently compatible with (X_test, y_test) data frames
##  The column names of the binary text features are all accounted for.
print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", y_test.shape)

X_train shape (12180, 88)
y_train shape (12180,)
X_test shape (4702, 88)
y_test shape (4702,)

# Create, train, score LogisticRegression model on unscaled data

In [16]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

/Users/henrytirado/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [17]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.6499178981937602
Testing Data Score: 0.5204168438962143

# Create, train, score RandomForestClassifier model on unscaled data

In [17]:
# Train a Random Forest Classifier model and print the model score

# Scale the data with StandardScaler

In [18]:
# Scaling the X data by using StandardScaler()
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

# Alternatively, scaling the data by using MinMaxScaler()
# scaler = MinMaxScaler().fit(X_train)
# X_train_scaled = scaler.transform(X_train)
# X_train_scaled

array([[-1.31172014, -1.31172014, -0.39311205, ..., -0.82658963,
        -0.81775408, -0.44297702],
       [-0.46579523, -0.46579523,  0.35168119, ..., -0.82658963,
         1.22286152, -0.44297702],
       [ 1.3364188 ,  1.3364188 ,  0.25400339, ..., -0.82658963,
         1.22286152, -0.44297702],
       ...,
       [ 1.67571549,  1.67571549, -1.34791257, ...,  1.20979016,
        -0.81775408, -0.44297702],
       [ 1.67600634,  1.67600634, -0.23438563, ..., -0.82658963,
         1.22286152, -0.44297702],
       [ 1.67906533,  1.67906533, -0.23438563, ...,  1.20979016,
        -0.81775408, -0.44297702]])

In [19]:
# Transforming the test dataset based on the fit from the training dataset
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-1.20255948, -1.20255948,  2.20755943, ..., -0.82658963,
        -0.81775408, -0.44297702],
       [-1.62943343, -1.62943343, -1.11348584, ...,  1.20979016,
        -0.81775408, -0.44297702],
       [-1.49837845, -1.49837845, -1.34791257, ...,  1.20979016,
        -0.81775408, -0.44297702],
       ...,
       [-1.10927546, -1.10927546, -0.72277464, ...,  1.20979016,
        -0.81775408,  2.25745345],
       [-1.10922531, -1.10922531, -0.91813024, ...,  1.20979016,
         1.22286152, -0.44297702],
       [-1.1091551 , -1.1091551 ,  1.23078141, ...,  1.20979016,
         1.22286152, -0.44297702]])

In [20]:
# Train the Logistic Regression model on the scaled data and print the model score
scaled_classifier = LogisticRegression()
scaled_classifier.fit(X_train_scaled, y_train)
print(f"Scaled Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Scaled Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Scaled Training Data Score: 0.6371921182266009
Scaled Testing Data Score: 0.5042535091450446

/Users/henrytirado/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score