In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [3]:
train_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,25200.0,0.1102,548.17,RENT,65000.0,Not Verified,n,42.67,0.0,1.0,...,10.0,0.0,0.0,282008.0,93765.0,57300.0,116320.0,N,N,low_risk
1,14000.0,0.2055,375.22,MORTGAGE,80000.0,Source Verified,n,15.47,0.0,0.0,...,75.0,0.0,0.0,434976.0,137629.0,17800.0,95032.0,N,N,low_risk
2,30000.0,0.1171,992.28,MORTGAGE,200000.0,Not Verified,n,14.14,0.0,0.0,...,100.0,0.0,0.0,99849.0,68769.0,13500.0,86349.0,N,N,low_risk
3,12000.0,0.1033,256.92,MORTGAGE,50000.0,Not Verified,n,21.41,0.0,0.0,...,33.3,0.0,0.0,209700.0,44654.0,13000.0,39700.0,N,N,low_risk
4,10625.0,0.1612,259.06,OWN,29000.0,Not Verified,n,25.87,0.0,0.0,...,0.0,0.0,0.0,35300.0,11893.0,18800.0,8000.0,N,N,low_risk

In [4]:
test_df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag,target
0,12000.0,0.2055,449.34,RENT,70000.0,Not Verified,n,28.56,0.0,1.0,...,60.0,1.0,0.0,68828.0,50387.0,21200.0,42628.0,N,N,low_risk
1,36000.0,0.0819,733.23,MORTGAGE,200000.0,Source Verified,n,11.38,0.0,0.0,...,28.6,0.0,0.0,380705.0,63917.0,64100.0,48417.0,N,N,low_risk
2,37225.0,0.1308,848.51,MORTGAGE,122700.0,Not Verified,n,16.83,0.0,0.0,...,100.0,0.0,0.0,101675.0,68475.0,34600.0,55477.0,N,N,low_risk
3,12000.0,0.1102,392.98,MORTGAGE,64500.0,Source Verified,n,36.63,0.0,2.0,...,14.3,0.0,0.0,234193.0,43389.0,42000.0,42279.0,N,N,low_risk
4,25000.0,0.1774,631.31,RENT,50000.0,Not Verified,n,33.82,0.0,0.0,...,10.0,0.0,0.0,146810.0,75919.0,83400.0,63410.0,N,N,low_risk

In [8]:
# Convert categorical data to numeric and separate target feature for training data
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

In [25]:
# Create the X feature vector (train data)
X_train = train_df.drop('target', axis=1)

# pd.dummies for all other categorical data
X_train = pd.get_dummies(X_train)
print(X_train.columns)
X_train.head()

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N'],
      dtype='object')

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,25200.0,0.1102,548.17,65000.0,42.67,0.0,1.0,20.0,0.0,3891.0,...,0,0,1,0,1,0,1,1,0,1
1,14000.0,0.2055,375.22,80000.0,15.47,0.0,0.0,19.0,0.0,12951.0,...,1,0,1,0,1,1,0,1,0,1
2,30000.0,0.1171,992.28,200000.0,14.14,0.0,0.0,7.0,0.0,12724.0,...,0,0,1,0,1,1,0,1,0,1
3,12000.0,0.1033,256.92,50000.0,21.41,0.0,0.0,14.0,0.0,8047.0,...,0,0,1,0,1,1,0,1,0,1
4,10625.0,0.1612,259.06,29000.0,25.87,0.0,0.0,10.0,0.0,6154.0,...,0,0,1,0,1,1,0,1,0,1

In [27]:
# Create the y-label (train data)
# Convert output labels to 0 and 1
le = LabelEncoder()
y_train = le.fit_transform(train_df['target'])
print("Label Encoder classes (train): ", le.classes_)
print("y_train (train): ", y_train)

Label Encoder classes (train):  ['high_risk' 'low_risk']
y_train (train):  [1 1 1 ... 0 0 0]

In [28]:
# Convert categorical data to numeric and separate target feature for testing data
X_test = train_df.drop('target', axis=1)

# pd.dummies for all other categorical data
X_test = pd.get_dummies(X_test)
print(X_test.columns)
X_test.head()

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'pymnt_plan_n', 'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N'],
      dtype='object')

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,verification_status_Source Verified,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,25200.0,0.1102,548.17,65000.0,42.67,0.0,1.0,20.0,0.0,3891.0,...,0,0,1,0,1,0,1,1,0,1
1,14000.0,0.2055,375.22,80000.0,15.47,0.0,0.0,19.0,0.0,12951.0,...,1,0,1,0,1,1,0,1,0,1
2,30000.0,0.1171,992.28,200000.0,14.14,0.0,0.0,7.0,0.0,12724.0,...,0,0,1,0,1,1,0,1,0,1
3,12000.0,0.1033,256.92,50000.0,21.41,0.0,0.0,14.0,0.0,8047.0,...,0,0,1,0,1,1,0,1,0,1
4,10625.0,0.1612,259.06,29000.0,25.87,0.0,0.0,10.0,0.0,6154.0,...,0,0,1,0,1,1,0,1,0,1

In [ ]:
# add missing dummy variables to testing set

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score